name: safeher_mobile_app
description: "SafeHer - Women's Safety Mobile Application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  cupertino_icons: ^1.0.8
  
  # Database & Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  
  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.4.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.7.4
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  
  # Notifications & Background Tasks
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.5.2
  
  # UI/UX Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utilities
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  uuid: ^4.2.1
  crypto: ^3.0.3
  
  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.2
  
  # Device Features
  vibration: ^1.8.4
  torch_light: ^1.0.0
  sensors_plus: ^4.0.2
  battery_plus: ^5.0.2
  device_info_plus: ^9.1.1
  
  # Authentication
  google_sign_in: 6.2.2
  flutter_facebook_auth: ^6.0.3
  
  # Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  # Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
