// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OJX5fwYO17_yvdqh78jIC72oQj6X04U',
    appId: '1:395420715715:web:1916bf2c17b4d76c977076',
    messagingSenderId: '395420715715',
    projectId: 'safeher-mobileapp',
    authDomain: 'safeher-mobileapp.firebaseapp.com',
    storageBucket: 'safeher-mobileapp.firebasestorage.app',
    measurementId: 'G-VXHB1223VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_8EcNjz7UjbB3VzV0BBfgxpRkwMBpZc',
    appId: '1:395420715715:android:59efdfbec4db09d8977076',
    messagingSenderId: '395420715715',
    projectId: 'safeher-mobileapp',
    storageBucket: 'safeher-mobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYAj5wAzttahhJDyhVzCMSiMMc5NJ2yQk',
    appId: '1:395420715715:ios:890b6b15581c969c977076',
    messagingSenderId: '395420715715',
    projectId: 'safeher-mobileapp',
    storageBucket: 'safeher-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.safeherMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYAj5wAzttahhJDyhVzCMSiMMc5NJ2yQk',
    appId: '1:395420715715:ios:890b6b15581c969c977076',
    messagingSenderId: '395420715715',
    projectId: 'safeher-mobileapp',
    storageBucket: 'safeher-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.safeherMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3OJX5fwYO17_yvdqh78jIC72oQj6X04U',
    appId: '1:395420715715:web:2a44e781516d08d8977076',
    messagingSenderId: '395420715715',
    projectId: 'safeher-mobileapp',
    authDomain: 'safeher-mobileapp.firebaseapp.com',
    storageBucket: 'safeher-mobileapp.firebasestorage.app',
    measurementId: 'G-NLQ10XLL00',
  );
}
